Begin work on Building Markers in street map.
toontown-archipelago/toontown-archipelago pull request #103
Opened 2024-07-24 21:01 UTC by RegDogg

Closes https://github.com/toontown-archipelago/toontown-archipelago/issues/91

2024-07-27 01:36 UTC, RegDogg commented
Ready to merge, must be merged with https://github.com/toontown-archipelago/panda3d/pull/4

2024-07-27 02:08 UTC, DarthMDev requested changes

2024-07-27 02:09 UTC, DarthMDev reviewed
some stuff that needs to be looked at

2024-07-27 02:21 UTC, RegDogg commented on toontown/quest/QuestMap.py
> +                elif quest.getType() not in (
Resolved in https://github.com/toontown-archipelago/toontown-archipelago/pull/103/commits/d84ac62d2a77b2599d428e4a8464a0e3e56c5b95

2024-07-27 02:21 UTC, RegDogg commented on toontown/quest/QuestMap.py
> +        if isSuitBlock: # Make the bubble appear gray if a cog took over a task building
Resolved in https://github.com/toontown-archipelago/toontown-archipelago/pull/103/commits/d84ac62d2a77b2599d428e4a8464a0e3e56c5b95

2024-07-27 03:09 UTC, DarthMDev approved these changes

2024-07-27 03:09 UTC, DarthMDev commented
LGTM!

2024-07-27 03:21 UTC, RegDogg reviewed
Final changes made, good to go for review from @DevvyDont

2024-07-27 06:49 UTC, DevvyDont approved these changes
lgtm! will merge this in when new engine build is ready

2024-08-04 22:38 UTC, RegDogg commented
Final changes made, ready for merge into https://github.com/toontown-archipelago/toontown-archipelago/tree/feature/cog-building-street-map when ready

2024-08-09 03:48 UTC, merged