add Damage Multiplier option to apworld
toontown-archipelago/toontown-archipelago pull request #45
Opened 2024-04-17 02:42 UTC by LittlestCube

I usually play with a damage multiplier and I thought others would enjoy it too.

Let me know if there's a better way to implement this.

2024-04-17 03:09 UTC, DevvyDont requested changes

2024-04-17 03:09 UTC, DevvyDont commented on toontown/toonbase/ToontownBattleGlobals.py
in order for our damage multiplier to be read properly on the server and for clients, we should add in an additional parameter for the `getAvPropDamage()` method. the specifics aren't important, just make sure that you adjust all usages of the method in the codebase to include `toon.getDamageMultiplier()` as a passed in parameter

also with damage multiplier being an integer from 10-500, right before we return the adjusted floored damage we can call
```py
damage *= damageMultiplier / 10
```

2024-04-17 03:09 UTC, DevvyDont commented on toontown/archipelago/distributed/DistributedArchipelagoManager.py
as mentioned previously, these methods should be moved to DistributedToon

2024-04-17 03:09 UTC, DevvyDont commented on toontown/archipelago/distributed/DistributedArchipelagoManagerAI.py
as mentioned previously, these methods should be moved to DistributedToonAI

also don't forget to add the `d_setDamageMultiplier()` and `b_setDamageMultiplier()` methods similarly to how other fields are defined

2024-04-20 02:37 UTC, LittlestCube commented on apworld/EXAMPLE_TOONTOWN.yaml
turns out i wanted to make it a normal modifier in the first place 🥴 i just didn't know what was meant by "global"

i decided to make the range 0-500 instead, include 0 because why not it's up to the player i guess :p

2024-04-21 04:21 UTC, DevvyDont approved these changes
lgtm!

2024-04-21 04:26 UTC, merged